import { Project } from 'projen';
import { GithubStepConfig, PipelineStep } from './step';

/**
 * Options for the CDK outputs summary step.
 */
export interface CdkOutputsSummaryStepOptions {
  /** The stage name used to identify the outputs file. */
  readonly stageName: string;
}

/**
 * A pipeline step that writes CDK stack outputs to the GitHub job summary.
 * This step reads the outputs JSON file generated by CDK deploy and formats
 * it as a markdown table in the GitHub Actions job summary.
 */
export class CdkOutputsSummaryStep extends PipelineStep {

  constructor(
    project: Project,
    private readonly options: CdkOutputsSummaryStepOptions,
  ) {
    super(project);
  }

  /**
   * Converts the step into a GitHub Actions step configuration.
   */
  public toGithub(): GithubStepConfig {
    const { stageName } = this.options;
    const outputsFile = `cdk-outputs-${stageName}.json`;

    // Create a bash script that reads the CDK outputs file and writes to GitHub summary
    const script = `
if [ -f "${outputsFile}" ]; then
  echo "## CDK Stack Outputs - ${stageName}" >> $GITHUB_STEP_SUMMARY
  echo "" >> $GITHUB_STEP_SUMMARY

  # Check if the file has content
  if [ -s "${outputsFile}" ]; then
    # Parse JSON and create a markdown table
    echo "| Stack | Output Key | Output Value |" >> $GITHUB_STEP_SUMMARY
    echo "|-------|------------|--------------|" >> $GITHUB_STEP_SUMMARY

    # Use jq to parse the JSON and format as table rows
    jq -r 'to_entries | .[] | .key as $stack | .value | to_entries | .[] | "| \\($stack) | \\(.key) | \\(.value) |"' "${outputsFile}" >> $GITHUB_STEP_SUMMARY

    echo "" >> $GITHUB_STEP_SUMMARY
  else
    echo "No outputs found for this deployment." >> $GITHUB_STEP_SUMMARY
    echo "" >> $GITHUB_STEP_SUMMARY
  fi
else
  echo "## CDK Stack Outputs - ${stageName}" >> $GITHUB_STEP_SUMMARY
  echo "" >> $GITHUB_STEP_SUMMARY
  echo "Outputs file not found: ${outputsFile}" >> $GITHUB_STEP_SUMMARY
  echo "" >> $GITHUB_STEP_SUMMARY
fi
`.trim();

    return {
      needs: [],
      steps: [
        {
          name: `Add CDK outputs to summary - ${stageName}`,
          run: script,
        },
      ],
      env: {},
    };
  }
}
