import { Project } from 'projen';
import { GithubStepConfig, GitlabStepConfig, PipelineStep } from './step';

/**
 * Options for the CDK outputs summary step.
 */
export interface CdkOutputsSummaryStepOptions {
  /** The stage name used to identify the outputs file. */
  readonly stageName: string;
}

/**
 * A pipeline step that writes CDK stack outputs to the CI/CD job summary.
 *
 * For GitHub Actions: Writes outputs as a markdown table to the job summary.
 * For GitLab CI: Displays outputs in a collapsible section in the job log.
 *
 * This step reads the outputs JSON file generated by CDK deploy and formats
 * it for display in the respective CI/CD platform.
 */
export class CdkOutputsSummaryStep extends PipelineStep {

  constructor(
    project: Project,
    private readonly options: CdkOutputsSummaryStepOptions,
  ) {
    super(project);
  }

  /**
   * Converts the step into a GitHub Actions step configuration.
   */
  public toGithub(): GithubStepConfig {
    const { stageName } = this.options;
    const outputsFile = `cdk-outputs-${stageName}.json`;

    // Create a bash script that reads the CDK outputs file and writes to GitHub summary
    const script = `
if [ -f "${outputsFile}" ]; then
  echo "## CDK Stack Outputs - ${stageName}" >> $GITHUB_STEP_SUMMARY
  echo "" >> $GITHUB_STEP_SUMMARY

  # Check if the file has content
  if [ -s "${outputsFile}" ]; then
    # Parse JSON and create a markdown table
    echo "| Stack | Output Key | Output Value |" >> $GITHUB_STEP_SUMMARY
    echo "|-------|------------|--------------|" >> $GITHUB_STEP_SUMMARY

    # Use jq to parse the JSON and format as table rows
    jq -r 'to_entries | .[] | .key as $stack | .value | to_entries | .[] | "| \\($stack) | \\(.key) | \\(.value) |"' "${outputsFile}" >> $GITHUB_STEP_SUMMARY

    echo "" >> $GITHUB_STEP_SUMMARY
  else
    echo "No outputs found for this deployment." >> $GITHUB_STEP_SUMMARY
    echo "" >> $GITHUB_STEP_SUMMARY
  fi
else
  echo "## CDK Stack Outputs - ${stageName}" >> $GITHUB_STEP_SUMMARY
  echo "" >> $GITHUB_STEP_SUMMARY
  echo "Outputs file not found: ${outputsFile}" >> $GITHUB_STEP_SUMMARY
  echo "" >> $GITHUB_STEP_SUMMARY
fi
`.trim();

    return {
      needs: [],
      steps: [
        {
          name: `Add CDK outputs to summary - ${stageName}`,
          run: script,
        },
      ],
      env: {},
    };
  }

  /**
   * Converts the step into a GitLab CI step configuration.
   * Creates a collapsible section in the job log to display CDK outputs.
   */
  public toGitlab(): GitlabStepConfig {
    const { stageName } = this.options;
    const outputsFile = `cdk-outputs-${stageName}.json`;
    const sectionName = `cdk_outputs_${stageName.replace(/-/g, '_')}`;

    // Create a bash script that reads the CDK outputs file and displays it in a collapsible section
    const commands = [
      `if [ -f "${outputsFile}" ]; then`,
      `  echo -e "\\e[0Ksection_start:\`date +%s\`:${sectionName}[collapsed=false]\\r\\e[0K📦 CDK Stack Outputs - ${stageName}"`,
      `  if [ -s "${outputsFile}" ]; then`,
      '    echo ""',
      '    echo "Stack Outputs:"',
      '    echo "=============="',
      `    jq -r 'to_entries | .[] | "\\n📚 Stack: \\(.key)\\n" + (.value | to_entries | .[] | "  • \\(.key): \\(.value)")' "${outputsFile}"`,
      '    echo ""',
      '  else',
      '    echo "No outputs found for this deployment."',
      '  fi',
      `  echo -e "\\e[0Ksection_end:\`date +%s\`:${sectionName}\\r\\e[0K"`,
      'else',
      `  echo "⚠️ CDK outputs file not found: ${outputsFile}"`,
      'fi',
    ];

    return {
      extensions: [],
      commands,
      needs: [],
      env: {},
    };
  }
}
